### ISSUE TITLE
wikidata label based location lookup

### ISSUE THREAD

**Issue by tholzheim** [somnathrakshit/geograpy3#36]
Given wikidata label such as "CA" lookup the possible locations such as "Canada", "California", ...

**Comment by WolfgangFahl** [comment]
Why would you want to go by Wikidata label? geograpy is about natural language to location conversion. So taking the natural language text "CA" as an input leads to ambigous results. Disambiguation is the goal and wikidata might help. So there is a difference between the task take "CA" as a wikidata label and look it up as this issue seems to propose and take "CA" as a natural language input and try to match a location for it which might lead to the region "CA" as in California/US or the country Canada with iso code CA. The second task is the broader one and can leverage the technical solution of task 1 for being solved.

**Comment by WolfgangFahl** [comment]
**LabelLookup example #2**

**query**
```sql
select * from RegionLookup where label in ('CA')

```
**result**
| label   | countryId                               | wikidataid                              | name       | iso   |      pop |   lat |   lon | countryName              | countryIso   |   CountryLat |   CountryLon |
|---------|-----------------------------------------|-----------------------------------------|------------|-------|----------|-------|-------|--------------------------|--------------|--------------|--------------|
| CA      | [https://www.wikidata.org/wiki/Q30 Q30] | [https://www.wikidata.org/wiki/Q99 Q99] | California | US-CA | 39144818 |    37 |  -120 | United States of America | US           |           40 |          -99 |

**Comment by WolfgangFahl** [comment]
**LabelLookup example #3**

**query**
```sql
SELECT * from CountryLookup WHERE label IN ('CA')

```
**result**
| label   | wikidataid                               | name   | iso   |      pop |   lat |   lon |
|---------|------------------------------------------|--------|-------|----------|-------|-------|
| CA      | [Q16](https://www.wikidata.org/wiki/Q16) | Canada | CA    | 37894799 |    56 |  -109 |
