### ISSUE TITLE
[BUG] UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by srancsik** [somnathrakshit/geograpy3#72]
**Describe the bug**
I can not run even the most simple example, due to UnicodeDecodeError.

**To Reproduce**

1. Absolutely virgin install of a virtual environment:
    python -m venv .venv

2. Install Geography package:
    pip install geograpy3

3. As the pypi package suggests, I enter the command: 
    geograpy-nltk
    **Here I get an error:** 
    geograpy-nltk : The term 'geograpy-nltk' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ geograpy-nltk
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (geograpy-nltk:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

4. I run the rest of the provided commands:
git clone https://github.com/somnathrakshit/geograpy3
cd geograpy3
scripts/install

5. I use the example provided:
import geograpy
url = 'https://en.wikipedia.org/wiki/2012_Summer_Olympics_torch_relay'
places = geograpy.get_geoPlace_context(url=url)

I get an error: 
Traceback (most recent call last):
  File "c:\Users\Balázs\PycharmProjects\Geograpy package test\main.py", line 3, in <module>
    places = geograpy.get_geoPlace_context(url=url)
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\__init__.py", line 24, in get_geoPlace_context
    places=get_place_context(url, text, labels=Labels.geo, debug=debug)
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\__init__.py", line 46, in get_place_context
    pc = PlaceContext(places)
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 32, in __init__
    self.setAll()
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 90, in setAll
    self.set_other()
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 206, in set_other
    self.other = [p for p in self.places if unused(p)]
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 206, in <listcomp>
    self.other = [p for p in self.places if unused(p)]
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 204, in unused
    return all(self.correct_country_misspelling(place_name) not in l for l in places)
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\places.py", line 204, in <genexpr>
    return all(self.correct_country_misspelling(place_name) not in l for l in places)
  File "C:\Users\Balázs\PycharmProjects\Geograpy package test\.venv\lib\site-packages\geograpy\locator.py", line 1105, in correct_country_misspelling
    for row in reader:
  File "C:\Python310\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 49: character maps to <undefined>

**Expected behavior**
I think I followed all the steps as described on https://pypi.org/project/geograpy3/, but not even the most basic code works

**Environment (please complete the following information):**
 - OS: [Windows 11]
 - Python Version [3.10.5]

**Comment by WolfgangFahl** [comment]
I am sorry to here that you are having so much trouble with the Windows/pyCHARM and python environment. This is unfortunately quite common. Alle the errors you are reporting are indicators of that environment giving you trouble.

There is only so much the geograpy team can do about this.

Your first problem is that the script that is being installed by pip install is not in your path. This might happen if your python and pip environment are not in sync or generally there is some kind of misconfiguation. You might want to try a linux environment for better being able to debug this situation. E.g. on linux there is a "which" command which will show you where a script has been installed. That geograpy-nltk is not in your PATH and not found is the first issue.

Please also provide your full "main.py" so that we could check what the problem might be. The cp1250 issues shows that there is something wrong with the string handling/decoding which is typical for the windows environment using https://en.wikipedia.org/wiki/Windows-1250 instead of UTF-8.

**Comment by srancsik** [comment]
Hello Wolfgang, 

Thank you for your email. 
Is there a way to install the geograpy-nltk manually somehow? Seems like the pip command does not install this, I would give it a manual try. 

Meanwhile about the main.py, I attempted to run this code:

import geograpy
url = 'https://en.wikipedia.org/wiki/2012_Summer_Olympics_torch_relay'
places = geograpy.get_geoPlace_context(url=url)

Thirdly, sure, thank you for the suggestion, I will try to replicate the same on Linux and will keep you posted.

**Comment by somnathrakshit** [comment]
@srancsik You should be able to install the package manually by downloading the source code and [building from source](https://github.com/somnathrakshit/geograpy3/blob/051061a1c7fcf2f2db549f3f547d8319a51a57e4/.github/workflows/upload-to-pypi.yml#L33).
Also, I see that you have created a virtual env for python. Did you also activate it using `source <env_name>/bin/activate`? I say this since I have seen lots of cases where users have forgotten to activate the newly created virtual env.
Lastly, in case you need it, here are the steps to add Python to your Windows PATH: https://www.makeuseof.com/python-windows-path/
